### PR TITLE
Update MechJeb2-dev.netkan

### PR DESCRIPTION
**Pull request by BasharMilesTeg**
Updates the spec_version, x_ci_version_base, ci and homepage fields

### CODE REVIEW

**Comment by techman83** [comment]
_nudge_ Where are you jenkins?

**Comment by techman83** [comment]
_poke_

**Comment by techman83** [comment]
Oh.. lol this is NetKAN-dev... Carry on!

**Comment by mheguy** [comment]
Looks good, merging with my thanks.

**Pull request merged**
